language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - ninja-build
      - libgtest-dev

before_install:
  - cd /usr/src/gtest && cmake . && make && mv libg* /usr/lib/
  - cd /usr/src/gmock && cmake . && make && mv libg* /usr/lib/

script:
  - cmake -G Ninja .
  - ninja
  - ./test/test.out
