language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - ninja-build
      - libgtest-dev
      - cmake

before_install:
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd /usr/src/gmock
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/

script:
  - cmake -G Ninja .
  - ninja
  - ./test/test.out
