language: cpp

# Install the Ninja build tool and CMake.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - cmake

# Install GTest and GMock from source (v1.8)
before_install:
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz -O googletest.tar.gz
  - tar -zxvf googletest.tar.gz
  - cd googletest-release-1.8.0/googletest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - sudo cp include/gtest/ /usr/include/ -rf
  - cd -
  - cd googletest-release-1.8.0/googlemock
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - sudo cp include/gmock/ /usr/include/ -rf
  - cd -

# Build and run the tests.
script:
  - cmake -G Ninja .
  - ninja
  - ./test/test.out
