language: cpp

# Installing GTest + GMock requires super permissions.
sudo: required

# Install the Ninja build tool, CMake, and graphviz
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - cmake
      - graphviz

before_script:
  # Install GTest and GMock from source (v1.8)
  - ./test/install_gtest_gmock.sh

# Build and run the tests.
script:
  - cmake -G Ninja .
  - ninja
  - ctest -V
