language: cpp

# Installing GTest + GMock requires super permissions.
sudo: required

# Install the Ninja build tool and CMake.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - cmake

before_script:
  # Install GTest and GMock from source (v1.8)
  - ./test/install_gtest_gmock.sh
  # Install graphviz `dot` utility
  - sudo apt-get install graphviz

# Build and run the tests.
script:
  - cmake -G Ninja .
  - ninja
  - ctest -V
