language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - ninja-build
      # - libgtest-dev
      # - google-mock
      - cmake

before_install:
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz -O googletest.tar.gz
  - tar -zxvf googletest.tar.gz
  - cd googletest-release-1.8.0/googletest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -
  - cd googletest-release-1.8.0/googlemock
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -

script:
  - cmake .
  - make
  - ./test/test.out
