language: cpp

# Install the Ninja build tool and CMake.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - cmake

# Install GTest and GMock from source (v1.8)
before_install:
  - ./test/install_gtest_gmock.sh

# Build and run the tests.
script:
  - cmake -G Ninja .
  - ninja
  - ./test/unittest.out
  - ./test/integrationtest.out 5
